### ISSUE TITLE
guide_colourbar_custom can't handle ticks with 2 elements

### ISSUE THREAD

**Issue by davidhodge931** [teunbrand/gguidance#9]
``` r
library(gguidance)
#> Loading required package: ggplot2
library(tidyverse)
library(palmerpenguins)

penguins |>
  ggplot() +
  geom_point(
    aes(x = flipper_length_mm,
        y = species,
        colour = flipper_length_mm)) +
  guides(
    colour = guide_colourbar_custom(),
  ) +
  theme(legend.ticks.length = ggplot2::rel(c(0.15, 0)))
#> Warning: Removed 2 rows containing missing values or values outside the scale range
#> (`geom_point()`).
#> Warning in gizmo_barcap(): Unable to check the capabilities of the png device.
#> Error in n_breaks < 1 || is_blank(element) || length == 0: 'length = 2' in coercion to 'logical(1)'
```

<sup>Created on 2024-04-27 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by teunbrand** [comment]
Thanks for the report David, you can see why I've labelled the package as experimental 😅 
Should be a straightforward fix.

**Comment by davidhodge931** [comment]
Thanks for the fixes!  

It's all weirder edge-case stuff anyway, but might as well fix if it's not too hard

**Comment by teunbrand** [comment]
Should no longer throw any errors:

``` r
library(gguidance)
#> Loading required package: ggplot2
library(tidyverse)
library(palmerpenguins)

penguins |>
  ggplot() +
  geom_point(
    aes(x = flipper_length_mm,
        y = species,
        colour = flipper_length_mm)) +
  guides(
    colour = guide_colourbar_custom(),
  ) +
  theme(legend.ticks.length = ggplot2::rel(c(0.15, 0)))
#> Warning: Removed 2 rows containing missing values or values outside the scale range
#> (`geom_point()`).
```

![](https://i.imgur.com/B7jkNp5.png)

Note that implementation differs from ggplot2, because of the 'little guides in a trenchcoat' approach.
To mirror ggplot2's approach to disabling ticks on one side, you can do the following:

``` r
penguins |>
  ggplot() +
  geom_point(
    aes(x = flipper_length_mm,
        y = species,
        colour = flipper_length_mm)) +
  guides(
    colour = guide_colourbar_custom(second_guide = "none"),
  )
#> Warning: Removed 2 rows containing missing values or values outside the scale range
#> (`geom_point()`).
```

![](https://i.imgur.com/GKVSSv2.png)

<sup>Created on 2024-04-27 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by davidhodge931** [comment]
Awesome, thanks! 

Minor thing - if your theme that you've added already has 2 elements in it, then there is a tick only every 2nd break even once you add `second_guide = "none"`

```
library(gguidance)
library(tidyverse)
library(palmerpenguins)

penguins |>
  ggplot() +
  geom_point(
    aes(x = flipper_length_mm,
    y = species,
    col = flipper_length_mm),
  ) +
  scale_colour_gradientn(colours = blues9, limits = c(NA, 220)) +
  theme(legend.ticks.length = rel(c(0, 0.5))) +
  guides(colour = guide_colourbar_custom(second_guide = "none"))
```
![image](https://github.com/teunbrand/gguidance/assets/55065152/1304eaba-5a88-4d7a-a395-261306e98671)

**Comment by davidhodge931** [comment]
In addition to above, are you planning on adding `second_guide` functionality to `guide_colourbar_custom` and `guide_colour_ring`?

**Comment by teunbrand** [comment]
> then there is a tick only every 2nd break

Yes but this is also what happens when you use e.g. `theme(axis.ticks.length.x.bottom = rel(c(0, 1)))`, so I'd say this is the typical outcome of specifying tick lengths.

> In addition to above, are you planning on adding second_guide functionality to guide_colourbar_custom and guide_colour_ring?

No they already have `first_guide` and `second_guide` arguments. It is dependent on the `legend.text.position` where the first and where the second is drawn. The colour ring has `inner_guide` and `outer_guide` arguments that have the same role, but are not dependent on the theme (as `legend.text.position = "outside"` is not a valid option).

**Comment by davidhodge931** [comment]
Re the 2nd break thing, it works differently to `ggplot2::guide_colourbar` which keeps all ticks in that situation.

Re the first_guide/second guide, whoops missed that

**Comment by teunbrand** [comment]
> it works differently to ggplot2::guide_colourbar which keeps all ticks in that situation.

True, but I'm not going to mirror that guide perfectly as I'd like to be free of the historic bagage of that guide so that I can do it the way I think it is best. Primarily, it is important to me that the tickmarks and labels are individual guides that can be tweaked as one sees fit separately from the colourbar itself. In the process, we might lose nuances like that, but it is still very much possible to achieve the same result.

**Comment by davidhodge931** [comment]
Fair enough - sounds like a good approach
